name    'amenezes-http_hardening'
version '0.2.0'
source 'http://github.com/amenezes/http_hardening'
author 'amenezes'
license 'Apache License, Version 2.0'
summary 'Puppet module to enable and manage http secure headers.'
description 'This a simple module to configure and manage secure http headers in web servers'
project_page 'http://github.com/amenezes/http_hardening'

dependency 'puppetlabs/stdlib', '>= 3.2.0 < 5.0.0'
