name    'amenezes-http_hardening'
version '0.2.4'
source 'http://github.com/amenezes/http_hardening'
author 'amenezes'
license 'Apache-2.0'
summary 'Puppet module to enable and manage secure http headers on web servers.'
description 'Puppet module to configure and manage secure http headers on web servers'
project_page 'http://github.com/amenezes/http_hardening'

dependency 'puppetlabs/stdlib', '>= 3.2.0 < 5.0.0'
dependency 'puppetlabs/concat', '>= 2.1.0 < 5.0.0'
